### ISSUE TITLE
Homework5

### ISSUE THREAD

**Issue by JSDenis** [LordKorvin/jsHome5#1]
При делении на 0 не должно быть Infinity, напиши ошибку вместо этого 
![Снимок экрана 2019-12-08 в 23 56 25](https://user-images.githubusercontent.com/32075762/70396071-769fac80-1a16-11ea-87e6-a639294429ee.png)

**Comment by JSDenis** [comment]
0! это 1 а не NaN 
![Снимок экрана 2019-12-08 в 23 59 38](https://user-images.githubusercontent.com/32075762/70396106-e9108c80-1a16-11ea-97a3-f93f1078b1ab.png)

**Comment by LordKorvin** [comment]
fixed
